version: '3.4'

services:
  sqlDb:
    container_name: sqlDb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  
  redis-master:
    container_name: redis-master
    restart: always    
    ports:
        - "6379:6379"
  
  redis-slave1:
    container_name: redis-slave1
    restart: always    
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
        - "6380:6379"
  
  redis-slave2:
    container_name: redis-slave2
    restart: always    
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
        - "6381:6379"

  testapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
    ports:
      - "8000:80"